services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "8443:443"
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception

volumes:
  mariadb-data:
  wordpress-data:

networks:
  inception:
    driver: bridge
