services:
  auth-service:
    build:
      context: ./backend/auth-service
    container_name: auth_service
    env_file:
      - ./secret/.env
    networks:
      - backend_network
      - frontend_network
  #  volumes:
  #   - auth_service_volume:/app
    ports:
      - "8000:8000"

  postgres:
    build:
      context: ./database
    container_name: postgres_db
    env_file:
      - ./secret/.env
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    networks:
      - backend_network


  nginx:
    build:
      context: ./nginx
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./frontend:/usr/share/nginx/html/frontend:ro
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - frontend_network
      - backend_network

networks:
  backend_network:
    name: backend_network
  frontend_network:
    name: frontend_network

volumes:
  #auth_service_volume:
  #  name: auth_service_volume
  postgres_data_volume:
    name: postgres_data_volume
